### ISSUE TITLE
Add the option to compare configurations between two given log files. 

### ISSUE THREAD

**Issue by erez-speedb** [speedb-io/log-parser#23]
This might be similar to https://github.com/speedb-io/log-parser/issues/12

**Comment by udi-speedb** [comment]
> This might be similar to #12

@erez-speedb - Seems so.
What I am going to do in #12 is to allow you to specify a baseline log explicitly and you would see the options diff between the parsed log and the selected baseline.
If that is the reason for this issue, please close it as duplicate. If not, please clarify how they differ.
Thanks

**Comment by udi-speedb** [comment]
@erez-speedb - Please close per my comment above or explain the differences. Thanks
