### ISSUE TITLE
Support new per-CF-statistics log entry

### ISSUE THREAD

**Issue by udi-speedb** [speedb-io/log-parser#55]
Once https://github.com/speedb-io/speedb/pull/801 is merged, the log parser needs to be updated accordingly. 
It should support both the existing display and the new one and automatically detect / handle either one.

**Comment by Yuval-Ariel** [comment]
plz add a picture of how it looks

**Comment by udi-speedb** [comment]
How what looks?
The artefacts should remain unmodified. It's just a matter of correctly parsing both an existing log and a log that has a separate dump per cf.

**Comment by Yuval-Ariel** [comment]
comment was intended for https://github.com/speedb-io/log-parser/pull/58
