### ISSUE TITLE
show no compaction events when there is none

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/log-parser#6]
when there are no flush events in the LOG the output is as shown in the picture. i think its best that the json shows something similar when there are no compaction events.
 
![image](https://github.com/speedb-io/log-parser/assets/105581454/b0ee8539-469e-45e4-b1c1-25d365cffa04)

**Comment by udi-speedb** [comment]
@Yuval-Ariel  Please explicitly describe the problem or problems you the issue is about.
Please also attach a log that shows the issue (without any identifying details such as the origin of the log file).

**Comment by udi-speedb** [comment]
@Yuval-Ariel If there is an issue with flushes as well, please open a separate issue for flushes. Thanks

**Comment by Yuval-Ariel** [comment]
@udi-speedb  updated decription. any LOG without compaction events will do
